# Generated by Django 3.2.7 on 2021-09-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='comment',
        ),
    ]
